name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Maven build
        run: ./mvnw -Dmaven.test.skip=true clean package
      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: |
            target/*.jar
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev-cicd'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app
      - name: Rename jar
        run: mv -v *.jar app.jar
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: app.jar
          TARGET: ${{ secrets.REMOTE_TARGET }}
